on: [pull_request]
name: Python Style Check
jobs:
  pycodestyle:
    name: pycodestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: pycodestyle
        uses: CS222-UIUC/course-project-group-7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRECOMMAND_MESSAGE: You have style errors. See them below.
